### ISSUE TITLE
Use dev dependencies for patch-package to reduce bundle size

### ISSUE THREAD

**Issue by bondparkerbond** [ds300/patch-package#138]
Currently, the README shows installation and usage of patch-package and related dependencies under regular dependencies. However, since this is just a script run during installation and building, adding the requisite package inside dev dependencies with the dev flag should be the recommended option so that we don't need to increase app bundle size.

**Comment by ds300** [comment]
Hi! :wave: Thanks for the question. This discussion has come up before: https://github.com/ds300/patch-package/issues/74 i came down on the side of omitting --dev from the readme.

However, since this is still causing confusion, I've just added a little caveat to the installation section of the docs.

Thanks again :pray:
