### ISSUE TITLE
Command not found: patch-package

### ISSUE THREAD

**Issue by juncoding** [ds300/patch-package#14]
Hello,

# run patch-package to create a .patch file
patch-package some-package

After "npm install patch-package", 
I run the command "patch-package" on terminal but got "zsh: command not found: patch-package".

I'm using macOS Sierra.

Please advise. 
Thanks.

**Comment by ds300** [comment]
either:

- if you're using yarn you can run `yarn patch-package <args>`
- otherwise `./node_modules/.bin/patch-package <args>`
- or add `./node_modules/.bin` to your $PATH environment variable (I prefer doing this)

It didn't occur to me that lots of people have not done that last option, so the instructions in the README won't work for them. I'll improve the README later.

**Comment by juncoding** [comment]
It works. thank you.

**Comment by ds300** [comment]
I decided not to modify the README because I can't figure out how to do so without sacrificing clarity. I hope that anyone who has the same issue you had will end up here via google or github search.

**Comment by pradeepdev001** [comment]
if you're using yarn--
Step 1: yarn add patch-package
Step 2: yarn patch-package <your patches || leave blank to run all at once>
        OR ./node_modules/.bin/patch-package <your patches || leave blank to run all at once>

if you're using npm--
Step 1: npm install patch-package
Step 2: patch-package <your patches || leave blank to run all at once>
        OR ./node_modules/.bin/patch-package <your patches || leave blank to run all at once>
