### ISSUE TITLE
create patch without new files.

### ISSUE THREAD

**Issue by PMExtra** [ds300/patch-package#146]
I want to create patch with modified files only, ignore the new files. How can I do?

I know I can use `--exclude` to ignore the path of new files, but I think it would be better if there is a parameter could ignore all the new files.

**Comment by ds300** [comment]
That's a cool suggestion, thanks!

You can also use `--include` to specify an allow-list kind of behaviour. e.g. if you're only changing one file called 'some-file.js' you can be like

     patch-package my-package --include some-file

or like this for multiple files like 'some-file.js' and 'other-file.js'

    patch-package my-package --include 'some-file|other-file'

 and that should ignore all the new files too.

I'm going to close this issue because it's a feature request and so far only one person has requested it, and it can be worked around quite easily using the above technique.
