### ISSUE TITLE
If patch failed, the process should exit with an error.

### ISSUE THREAD

**Issue by aabuhijleh** [ds300/patch-package#159]
Right now, if patching a package fails for some reason, for example, if file to be patched is not found, a warning is printed on the terminal and the process continues.

`
Warning: Patch file found for package **package-name** which is not present at ...
`

This is potentially dangerous and could break things in an application.

I propose that this is not enough and that the process should be exited and not allowed to complete execution and an error should be clearly indicated.

**Comment by KonstaL** [comment]
+1 
This just caused some problems with our production build. 
If defaulting a an error is too much, the error level should be configurable through a flag. 

For example:
```patch-package --fail-on-warning```

**Comment by johansedgeware** [comment]
Definitely +1 on this. Had similar problem as KonstaL

**Comment by Slessi** [comment]
@ds300 unfortunately this causes a new problem for me when I have a patch for a package in `devDependencies` and later run `yarn --production`

the patch fails due to module not being present, which is expected for me as im trying to install production modules only

**Comment by ds300** [comment]
Ah, I'm very sorry about that @Slessi I'm working on a fix!

**Comment by ds300** [comment]
Ok @Slessi I pushed a fix to v6.2.0 you probably don't need to do anything except upgrade but read this just in case: https://github.com/ds300/patch-package#dev-only-patches

**Comment by Boxonical** [comment]
Hi, I'm running microservices, all the services shared a "patches" folder.
ie. list of patches
1. datapumps
2. loopback-connector-mongodb
3. modem

If file to be patched is not found:
Expected behavior - The process continues. 
Current behavior - The process exits. (if patch #2 not found, only patch #1 is applied)

Whether the process exits or not, should this be a flag (ie. --fail-on-warning) instead ?

**Comment by JackCA** [comment]
I also would love an option to ignore these errors.

I'm doing docker-based yarn workspace microservice deploys where some packages that are patched may not exist.

But I've added the ones to be ignored to my `.dockerignore`, so that's another option besides symlinking if you're doing something docker-based.
