### ISSUE TITLE
Doesn't work with local NPM dependencies

### ISSUE THREAD

**Issue by mlabrum** [ds300/patch-package#16]
Hey,
Looks like there's an issue if you use a local npm file:// path as a dependency

☑ Creating temporary folder
☑ Building clean node_modules with npm
npm ERR! code ENOLOCAL
npm ERR! Could not install from "..\common" as it does not contain a package.json file.

Thanks,

**Comment by mlabrum** [comment]
It looks like the package.json file is being copied across and the relative path is fixed there, but the package-lock.json gets copied across with the releative path, and doesn't get fixed

**Comment by ds300** [comment]
That makes sense. Thanks for the report, I'll fix it tonight.

**Comment by ds300** [comment]
@mlabrum looks like you're running windows? This issue doesn't seem to happen on macOS - I have a potential fix for it but don't have easy access to a windows machine to test. Will have to wait until tomorrow afternoon probably.

**Comment by ds300** [comment]
@mlabrum Found a windows laptop to test on, but still can't reproduce the issue. Do you mind testing whether the issue is fixed if you add patch-package to your project with this version string: `git+https://github.com/ds300/patch-package#43a32991331eaec7017fd6c82fda64d7e4ea6a8e`

If not, what version of npm are you using? Are you running patch-package from git bash or some other way?

**Comment by ds300** [comment]
I still haven't been able to reproduce this issue, and there have been a lot of windows-related fixes since this issue appeared, so I'm going to close it due to inactivity. Feel free to reopen if you find you're still encountering the issue.

**Comment by Vi-dot** [comment]
Hello,

I also have this issue, on Ubuntu.
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "ext/ng2-pdf-viewer" as it does not contain a package.json file.
```

I edited a file inside `project/node_modules/pdfjs-dist`.
Then I launched `npx patch-package pdfjs-dist`.

Here is the `project/package.json`
```json
  "dependencies": {
    "ng2-pdf-viewer": "./ext/ng2-pdf-viewer",
    "pdfjs-dist": "^1.9.602"
    [...]
  },
  "devDependencies": {
    "patch-package": "3.5.0"
    [...]
  }
```

Here is the `project/ext/ng2-pdf-viewer/package.json`
```json
  "peerDependencies": {
    "pdfjs-dist": "^1.9.602"
  },
  "dependencies": {
    "pdfjs-dist": "^1.9.602"
  },
  "devDependencies": {
    [...]
  }
```

Same bug, with or without peerDependency.

Thanks

**Comment by ds300** [comment]
Hi @Vi-dot 

You should use the `file:` prefix for local dependencies. so `"ng2-pdf-viewer": "./ext/ng2-pdf-viewer",` becomes `"ng2-pdf-viewer": "file:./ext/ng2-pdf-viewer",`

It's not clear to me whether relative paths without a `file:` prefix are valid in a package.json dependency string. I could add support for them anyway, since they do seem to be supported unofficially at least.
