### ISSUE TITLE
Can't include package.json even after using --include

### ISSUE THREAD

**Issue by DDChiang** [ds300/patch-package#177]
I'm having trouble including a change on a `package.json` file I made for a node module.

I read docs and followed instructions on how to bring in an excluded file.

The command I ran: `yarn patch-package @optimizely/optimizely-sdk --include package.json`

Even after running the patch-package command with `--include` and confirming I saved changes to the module's package.json, the patch-package command still exits and I see the following messages in my terminal:
- ☑ Creating temporary folder
- ☑ Building clean node_modules with yarn
- ☑ Diffing your files with clean files
- ⁉️  Not creating patch file for package '@optimizely/optimizely-sdk'
- ⁉️  There don't appear to be any changes.

Am I missing something?

**Comment by DDChiang** [comment]
Fyi, I've also saw another comment on using `--exclude`. This doesn't work for me either :/ 

Command ran: `yarn patch-package @optimizely/optimizely-sdk --exclude '^(?!.*flip)'`

**Comment by ds300** [comment]
Hi! :wave:


The problem in the first case (supplying only `--include`) is that `--exclude` still has a default value of `'package.json$'`. In the second case your `--exclude` flag is still excluding `package.json` because it's matching all strings which do not contain 'flip', I think.

Try something like `yarn patch-package @optimizely/optimizely-sdk --exclude '^$'`

**Comment by ds300** [comment]
Gonna close this due to inactivity, feel free to open a new issue if you're still having trouble 🙏

**Comment by CharlieHess** [comment]
Might wanna document this tweak somewhere, since package.json is a very common place to inject patches.
