### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by DanielRuf** [ds300/patch-package#182]
I would like to move this project to GitHub Actions which is more flexible and faster.

Can we do that and did you already signup for the GHA beta?

PS: It might be good to move this repo to an org in the future and invite more maintainers =)

**Comment by ds300** [comment]
Yeah github actions seem neat. I've been thinking of adding an auto-publish step to this repo so that would be an ideal time to migrate.

Not sure about an org for patch-package though. It's my baby and it's in maintenance mode now so I don't expect any other significant feature contributions or refactoring unless PnP takes off (or something else happens to shake up JS package management). At that point it might make sense to move to an org if there are other people interested in doing that work rather than me.
