### ISSUE TITLE
Not able to include package.json in the patch

### ISSUE THREAD

**Issue by davidlampon** [ds300/patch-package#49]
I was commenting on [here](https://github.com/ds300/patch-package/issues/36) as we are (for some unknown reason so far) not able to download the latest beta version which seem to fix the issue about the error after applying a patch.

@ds300 let me explain out situation so maybe you can point the way to go. We are having [this issue](https://source.xing.com/frontend/malt/issues/2707): a third party package we are using has not properly set the folder directories to point to the `/lib` and `/es` folders. 

We opened this PR for them to merge but even if that happens then the other package we want to use [rc-slider](https://www.npmjs.com/package/rc-slider). So in total this means waiting on two external PRs.

As a workaround we wanted to modify or local packages, patch them, to allow this changes which already make our build succesful but we are not able to include the `package.json`file. We tried `yarn patch-package rc-util --use-yarn --exclude /$.^/` as a void regexp to reenable the disbales package.json tracking for the patch but with no success.

As another workaround we modified the `/es` files to patch the package but the patch-package is presenting the whitespace error `This is usually caused by inconsistent whitespace in the patch file.`

**TL,DR: What would be the way to include `package.json`in the patch?**

**Comment by ds300** [comment]
Hi! 👋 Thanks for the thorough explanation :-)

The first thing I noticed is that you're using JS-style regexp literals with the --exclude override. Instead you should use regular strings. See the examples in [include-exclude-paths.sh](https://github.com/ds300/patch-package/blob/master/test/include-exclude-paths/include-exclude-paths.sh) – particularly [this one](https://github.com/ds300/patch-package/blob/e5491304fc1050c14810abad7b3be40ec7d0634e/test/include-exclude-paths/include-exclude-paths.sh#L40) which uses interesting regexp syntax. Imagine you were passing the string to `new RegExp(...)`

Thanks for bringing this issue to my attention. I'll try to improve that section of the readme.

**Comment by dawnmist** [comment]
If you can add an example for disabling the default exclude, that'd be fantastic.

The other time that being able to patch package.json is desirable is when adding typescript type definitions to a package that doesn't have its own type definitions, so that you can add the "types" field to the package's package.json file pointing to your new type definition file.

**Comment by ds300** [comment]
Just published a fix for this in patch-package@6.0.0-4 – Thanks for pointing this out @dawnmist and @davidlampon :bow: :heart:

I'll close this once v6 leaves beta.

**Comment by ds300** [comment]
Hi @brunolemos :wave: !

Unfortunately what you want to do is not possible 😢 This is a common question about patch-package. I don't know of a way to get absolute control over which transient dependencies get installed. The best thing I've found is manually editing your own lock file, but that's only useful for making sure a specific version gets installed.

**Comment by ivikash** [comment]
I am trying to patch a dependency of a dependency on package.json. It does generate the patch fill with a little noise (using npm) but is unable to apply the patches -> `**ERROR** Failed to apply patch for package somePackage`. Can you include a short summary or documentation on the usage, like how to generate the patch file and specially what should be done in `prepare` step. I am currently using `6.0.0-v5` due to some constraints.

**Comment by ivikash** [comment]
@ds300 Any update on this? Also, as I am using `npm` so should the `patch-package` be applied on `prepare` or `postinstall`? While trying with `preinstall` its throwing an error saying patch-package is not found.

**Comment by ds300** [comment]
Closing this to tidy up, final 6.0.0 release will happen soon :tada:

**Comment by nerdaliciousCH** [comment]
How to make an empty --exclude that doesn't match anything?? so --include 'package\\.json$' --exclude '$'. That doesn't work for me :D

**Comment by dawnmist** [comment]
@nerdaliciousCH try making up a string that might be a filename but isn't.
e.g. `--exclude 'IAmNotARealFile.txt'`

The '$' in a regexp string means "at the end of the line" (or "end of the string" for something like filename strings). By having nothing before the $, you're actually matching _every filename_ because every filename will have an end of the string.

**Comment by xstable** [comment]
I use npx to run patch-package.
If I check for the Version I got: 
```bash
npx patch-package -v
patch-package 6.2.0
```

So I'm right, that the include && exclude funcitonality still not implemented?
I use this:
`postinstall": "patch-package --include 'package.json$' && jetify"`
or double-escaped like this:
`"postinstall": "patch-package --include 'package\\.json$' && jetify"`

Both don't recognize the changes in package.json.

**Comment by dawnmist** [comment]
The `--include` and `--exclude` options are there - but they're used when creating patches for other packages, not during postinstall (where you're applying patches to the various npm packages). You also need to be providing the `--exclude` option to override the default setting if you want to include changes to the package.json in the patch.

So to use it, you would first:
* Modify the files inside the `node_modules/package-to-be-patched` so that they contained what you needed, then
* Create the patch for the package using:
```
patch-package --exclude 'nothing' package-to-be-patched
```
* Check that the patch file generated contains what you expected it to. If not, return to step 1 to update the contents of the package that you want to patch so that it reflects the correct information and redo the patch creation again.
* Then set up postinstall so it applies the generated patches after each installation:
```
"postinstall": "patch-package && jetify"
```

You won't be able to change the dependencies in another project's package.json, because the patch is only applied after the dependencies have been installed. But you can do things like add a typescript type definition file to a project and update its package.json file to point to your new types.

**Comment by DominikGuzei** [comment]
@dawnmist why not remove the default for `--exclude`? If we don't make changes to the package.json it wouldn't be picked up anyway, right?

**Comment by dawnmist** [comment]
> @dawnmist why not remove the default for `--exclude`? If we don't make changes to the package.json it wouldn't be picked up anyway, right?

You'd probably be better asking the project maintainer that question. I am just someone who uses patch-package (and highly recommends it for certain tasks) who also had to work out how to make changes to the package.json work (for adding typescript types to a few packages).

That said, my suspicion is that it's because any patch you apply to the npm package's package.json is only applied after all its dependencies have already been installed - so most changes you could potentially make to the npm package's package.json file would be applied too late for them to actually do what you intend them to do. If those changes were included by default, many people would try to use them in situations where they do not work and the maintainer would forever be answering issues about things like "I modified the package's dependencies using patch-package, but npm/yarn are still installing the old ones!?" due to people not understanding that the modification only gets applied _after_ all packages are installed.

**Comment by DominikGuzei** [comment]
@dawnmist makes sense, thanks for the detailed explanation! 👍 sorry for the mistake 😅

**Comment by JellyL** [comment]
I think `--exclude 'nothing'` should be the default setting

**Comment by perrin4869** [comment]
I think the biggest case for `--exclude 'nothing'` is that one common requirement is to modify the `exports` field of a `package.json` file - due to many of them lacking exports for esm modules yet

**Comment by devinrhode2** [comment]
I don't think anyone mentioned this idea yet
But as typically we have 1000's of npm packages, this means most individual npm packages are not that huge.

If we tweak our gitignore to ignore all `node_module` folders like so:
```
node_nodules/*
```
We can then INCLUDE a certain `node_module` sub-folder in our git repo:
```
!node_modules/rc-slider
```
I think this may altogether be a better approach than patch-package, unless the package you are touching is huge. By simply checking the node module into git directly, there's a lot of nice simple benefits

**Comment by pkit** [comment]
For people who want to actually change dependencies: use yarn ["resolutions" ](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) although it's not perfect (cannot install a new package that didn't exist before), it covers a lot of cases.

**Comment by pkit** [comment]
> By simply checking the node module into git directly, there's a lot of nice simple benefits

Dunno, looks like that approach gives zero new features compared to `patch-package`, but pollutes the repo with a bunch of garbage.
Any examples of the benefits?
