### ISSUE TITLE
Allow to pass commands to install command (yarn/npm)

### ISSUE THREAD

**Issue by JCMais** [ds300/patch-package#59]
We currently are using some deps that have too strict engine settings, this makes them fail when installing normally.

So we need to use `yarn install --ignore-engines`, and since this package has to do a clean install of the packages to generate a patch file, it does not work.

The workaround is to define `ignore-engines` globally, but it would be great if we could pass extra params to the install arg

**Comment by ds300** [comment]
Thanks for the report! Sorry it took me so long to get around to dealing with this. I added `--ignore-engines` to the yarn invocation. The only other option people might want to pass is `--ignore-scripts` which nobody has asked for yet, so I'll wait until there's demand before I refactor to handle that.

Otherwise, I just published the fix for this in 6.0.0 :tada: thanks again!

**Comment by EricMCornelius** [comment]
@ds300 - finding I could precisely use `--ignore-scripts` to handle patching some native dependencies requiring compilation during installation, now that 12.x is out.

And recommendations? Shall I try to raise a similar PR?
