### ISSUE TITLE
Checking out fresh node_modules takes a long time with a big project

### ISSUE THREAD

**Issue by KevinVlaanderen** [ds300/patch-package#64]
I am working currently working on a MR to improve the speed of patch-package, specifically the checking out of a fresh copy of the node_modules. However, I encountered an issue with how this currently works.
You can currently patch any module within the root of your node_modules, including modules that are not listed in your package.json (i.e. transitive dependencies). This implicitly relies on the behavior of the package manager, because the location of such modules is not guaranteed. Transitive dependencies can end up either in the root of your node_modules (if there are no conflicting version requirements) or as sub node_modules. Specific behavior depends on whether you're using npm or yarn (and which version of them).

I think it's a bad idea to rely on this implicit behavior, but I'm not sure what the proper solution is. I can think of the following directions:

- Patched modules must be mentioned explicitly in your node_modules. The system should throw an error otherwise.
- The relevant version of the patched node_modules is looked up in its package.json. This is used to check out a fresh copy. This relies on the fact that people do not patch the version number in the module's package.json.
- The version number is somehow derived from the lock file.

What do you think?

**Comment by KevinVlaanderen** [comment]
Hi @ds300 ,

What are your thoughts on the issue outlined above? I think there is room for some nice performance improvements, but we'll have to get the acceptance criteria right.

**Comment by ds300** [comment]
Hi Kevin! :wave:

Thanks for your thoughts on this. I too have considered selectively installing only the packages to be patched. Performance hasn't been a priority so far, most people don't seem to mind waiting 5-25s or so for their packages to install in order to generate a patch file.

Having said that, the current approach to diffing files is very much 'brute force', and it should be totally possible to get it in the 0-3 seconds range for a project of any size unless the package to be patched has a node-gyp compile step or something. if you're happy to implement something equally robust but more nimble I'd love to include it :) Definitely looking at the lock file and reproducing the relevant subtree is the approach to explore first.

I was also worried about allowing transient dependencies to be patched. Luckily nobody has raised issues about it so far. I think that lock files sufficiently reduce the risk of churn?

I'd be worried that asking users to turn transitive dependencies into direct dependencies might cause frustration, because then if they remove the package that depended on it they might end up not needing the patched package. Also, the user would need to be careful with version ranges because they might add a direct version that is not compatible with the transitive version and end up not actually patching the relevant version.

Cheers!

**Comment by ds300** [comment]
I've implemented this now, including support for explicitly patching transitive dependencies. It's published in `patch-package@6.0.0-12` but haven't documented the transitive deps stuff yet.
