### ISSUE TITLE
Why is there a custom implementation for applying patches?

### ISSUE THREAD

**Issue by KevinVlaanderen** [ds300/patch-package#71]
Instead of using e.g. git apply?
Reason I am asking is that we noticed some odd behavior. For example, new folders are not created. Git diff will do so just fine.
Git is already assumed to be present and is used for creating the diff.
Maybe I missing something. I'm curious to hear your thoughts.

**Comment by ds300** [comment]
`git apply` has subtly inconsistent behaviour across versions and platforms, especially with respect to whitespace. It cost me a lot of effort to debug issues with it, and I eventually gave up and decided to implement the patch application myself. It's still not quite finished. The new folder bug you raised is a good example of how it's not done yet :D Otherwise it's in pretty good shape and already has more consistent behaviour than `git apply`. The main thing remaining to implement is support for changing file modes.

Git is assumed to be present at patch-creation time, and was previously assumed to be present at patch-application time too, but that's no longer necessary. I remember someone complaining that they didn't have git in their build container, though it is rare.

**Comment by ulrichb** [comment]
> to be present at patch-application time too, but that's no longer necessary

Nice!

**Comment by ds300** [comment]
I'm closing this to tidy up. The patch application code is very solid now 😃
