### ISSUE TITLE
PnP (Yarn) support

### ISSUE THREAD

**Issue by DanielRuf** [ds300/patch-package#83]
There is the new Plug'n'Play concept which makes node_modules obsolete:

https://github.com/yarnpkg/rfcs/pull/101

https://github.com/yarnpkg/yarn/pull/6382

https://www.reddit.com/r/node/comments/9fh89w/yarn_plugnplay_getting_rid_of_node_modules/

**Comment by DanielRuf** [comment]
I plan to roll out PnP as standard in our internal processes and would like to ensure that we can still use patch-package.

**Comment by nhducit** [comment]
I was wonder how can I use patch-package with PnP. Glad to see that you addressed the problem already

**Comment by thymikee** [comment]
Just a ping that PnP is now officially available on latest Yarn v1.12. Sounds like a fair contribution to the project if anybody has some time 😉

**Comment by ds300** [comment]
I got around to thinking about how to add PnP support. It could be a real challenge.

- The good news is that we wouldn't need a postinstall hook to apply patches :tada:
- The bad news is that we'd need to patch the `.pnp.js` file unless yarn adds support for extending the PnP resolver. The patching would probably need to be done with a postinstall hook (~:tada:~)
- We'd also need to have a project-local cache for patched files e.g. `.patch-package/`
- The workflow would probably be:
   1. `yarn unplug`
   2. Fix issues
   3. Run `patch-package <package-name>`
   4. `yarn` to remove unplugged package if you're done

questions:

- Do we really need to patch `.pnp.js`? Could involve lots of breakage with new yarn versions.
- Will this work with the various loaders (jest, webpack, etc?) seems like it should
- Seems like yarn PnP still doesn't run `postinstall` or `postuninstall` on `yarn remove` and with PnP the `postinstall-postinstall` trick wouldn't work, so would need to figure out a new way to trigger a script on `yarn remove` if patching `.pnp.js` is required. Probably we should just fix the long-standing yarn bug https://github.com/yarnpkg/yarn/issues/3628
- Does `yarn unplug` support specifying package versions?

**Comment by DanielRuf** [comment]
cc @arcanis

**Comment by TroyAlford** [comment]
Any news or updates on this front?

**Comment by ds300** [comment]
Nope. Seems like pnp hasn't taken off outside Facebook. Yarn 2 seems to be coming along but not sure how many early adopters there are yet or whether patch-package needs to be adapted for it until pnp gets more traction. I'm curious now so will look into it!

**Comment by arcanis** [comment]
> Nope. Seems like pnp hasn't taken off outside Facebook.

Amusingly it's the opposite: Facebook doesn't use PnP (they hit problems to integrate it with their Buck-based build systems), but its development is going strong thanks to the community that surrounds it. PnP is a just a bit more than a year old, and the progress we've made are frankly staggering! 🙂

We'll remain in beta for at least a few more weeks until we can solve the last remaining compatibility issues, but we've already been using the v2 in various projects with a lot of success. Next, CRA, Gatsby, Webpack, Husky, Angular, we've worked with all those projects (and more) and their maintainers have generally been very supportive.

Fwiw I sometimes hear people mentioning patch-package during the Q&A parts of my talks, so I'd be happy to help you solve this issue by providing feedback or implementing the necessary changes on the Yarn side. Ping me on [Discord](https://discord.gg/yarnpkg) if you want to chat!

**Comment by ds300** [comment]
Wow, thanks so much for the update @arcanis ♥️ That's exciting news! I'll schedule some time to look into it.

**Comment by arcanis** [comment]
I have a somewhat huge update: Yarn v2 now supports builtin patches 🎉 Similar capabilities were required for some other compatibility work I was doing, and I took the opportunity to implement a truly generic way to patch packages.

For all the gory details you can find [my Yarn PR](https://github.com/yarnpkg/berry/pull/647), but in short:

- Yarn now supports a `patch:` protocol 
- Both the original and the patches are stored within the cache & the lockfile
- (In progress) Plugins can define their own "builtin patches", so in my mind a `patch-package` plugin would simply load all the patch files inside a specific directory, create resolution descriptors for each of them, and replace the dependency descriptors through a hook.

I forked the `apply.ts` file from `patch-package` and [made some modifications](https://github.com/yarnpkg/berry/blob/master/packages/plugin-patch/sources/tools/apply.ts) in order to make it support our filesystem abstraction. I think the one thing I'd like to fix is the mechanism used to load the hunks; at the moment they must be within a fixed range, but it may not work very well with different releases of a same package distributed through minified files (ex: TypeScript). The regular `patch` utility doesn't have min/max offset, so I'd like to do the same.

If someone wants to give us a hand it would be most appreciated - in particular, the developer experience around generating the patchfiles could probably be improved or at least better documented. Help wanted!

**Comment by NoahAndrews** [comment]
@arcanis Does Yarn 2 support patching the dependencies of packages like [patch-package does](https://github.com/ds300/patch-package#nested-packages)?

**Comment by merceyz** [comment]
@NoahAndrews Yes it does, you can use resolutions to change a dependency to use your patched version instead https://yarnpkg.com/configuration/manifest#resolutions

**Comment by dreyks** [comment]
do we have a solution for this?

**Comment by DanielRuf** [comment]
@dreyks I think the direct support for patches in yarn might be sufficient.
There has happend much since this issue was opened. yarn v1 (classic) received new features and bugfixes and yarn berry was finally released.

https://github.com/ds300/patch-package/issues/83#issuecomment-569256924

**Comment by merceyz** [comment]
Yes, read https://github.com/ds300/patch-package/issues/83#issuecomment-569256924

**Comment by alamothe** [comment]
@arcanis I am trying to use the patch functionality for `@types/react`. I was able to create a patch successfully, but when I add as a dep:
```
    "@types/react": "patch:@types/react^17.0.0#../patches/@types+react.patch",
```
The output of `yarn install` is:
```
~/Projects/example/cra $ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0035: │ @types/react^17.0.0@npm:unknown: The remote server failed to provide the requested resource
➤ YN0035: │   Response Code: 404 (Not Found)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.yarnpkg.com/@types%2freact^17.0.0
➤ YN0000: └ Completed in 0s 447ms
➤ YN0000: Failed with errors in 0s 452ms
```
What am I missing?

**Comment by alamothe** [comment]
It seems like `/` shouldn't be escaped. Please help

**Comment by alamothe** [comment]
Got it to work with:
```
"@types/react": "patch:@types\\react@17.0.0#../patches/@types+react.patch",
```
after some tinkering.
